// =============================================================================
// AyushBot Sensor Pack — TFLite Micro Model Data (INT8 Quantized)
// =============================================================================
//
// PURPOSE:
//   This header file contains the serialized TensorFlow Lite Micro model as a
//   C byte array. The model is a quantized Decision Tree (depth 5) compiled to
//   INT8 fixed-point arithmetic for execution on the Arduino Nano 33 BLE.
//
// HOW THIS FILE IS GENERATED:
//   This file is NOT hand-written. It is the output of the TinyML training
//   pipeline in ml/tinyml/. The generation process is:
//
//   1. A Decision Tree classifier is trained in Python (scikit-learn) on the
//      MIMIC-IV vital signs cohort (70,341 ICU admissions).
//   2. The trained model is exported to TensorFlow Lite format
//      (or via Edge Impulse's export pipeline).
//   3. Post-training INT8 quantization is applied — weights and thresholds
//      are converted from float32 to int8 representation. For decision trees,
//      this quantization is lossless (tree splits are exact comparisons).
//   4. The .tflite binary is converted to a C header file using the xxd
//      utility or TFLite Micro's built-in converter:
//        xxd -i model.tflite > model.h
//   5. This produces a const unsigned char array (the model bytes) and a
//      const unsigned int variable (the model size in bytes).
//
// MODEL SPECIFICATIONS:
//   - Architecture:    Decision Tree, max depth 5
//   - Input features:  6 (SpO2, HR, Temperature, Age_months, ΔSpO2, ΔHR)
//   - Output:          Binary classification (DANGER=1, SAFE=0) with confidence
//   - Quantization:    INT8 fixed-point (lossless for tree structures)
//   - Size:            ~4.2 KB (fits comfortably in 1 MB Flash)
//   - Inference time:  ~0.4 ms on Cortex-M4 @ 64 MHz
//   - Threshold:       0.32 (high sensitivity — catches 96% of true dangers)
//
// ACHIEVED METRICS (from training pipeline):
//   - AUC:             0.92
//   - Sensitivity:     0.96 (at threshold 0.32)
//   - Specificity:     0.87
//   - Power draw:      ~18 mW during inference
//
// IMPORTANT:
//   Do not edit this file manually. Regenerate it by running the training
//   pipeline in ml/tinyml/ and copying the exported header here.
//
// The actual byte array will be placed here after model training:
//   const unsigned char g_model_data[] = { ... };
//   const unsigned int g_model_data_len = ...;
// =============================================================================
