#pragma once

// =============================================================================
// AyushBot — TFLite Micro Model (INT8 Quantized Decision Tree)
// AUTO-GENERATED by ml/tinyml/train.py — do not edit manually
// Replace this placeholder after running the training pipeline:
//   xxd -i model.tflite > model.h
// =============================================================================

const unsigned char g_model_data[] = { 0x00 };
const unsigned int  g_model_data_len = 1;