# =============================================================================
# AyushBot Backend — Authentication & Authorization Module
# =============================================================================
#
# PURPOSE:
#   Validates API requests from ASHA Android phones and administrative tools.
#   Ensures only authorized devices can access the triage API.
#
# AUTHENTICATION MECHANISM:
#   API Key authentication (not OAuth/JWT — intentionally simple for the
#   offline PHC environment where there's no identity provider).
#
#   How it works:
#     1. During PHC setup, each ASHA's phone is provisioned with a unique
#        API key (generated by the admin script, stored securely on the phone)
#     2. The phone sends the key in the X-API-Key HTTP header with every request
#     3. This module validates the key against a local key store (SQLite table
#        or config file)
#     4. If valid: extract the ASHA ID associated with the key for audit logging
#     5. If invalid: return HTTP 401 Unauthorized
#
# KEY MANAGEMENT:
#   - Keys are 256-bit random tokens, hex-encoded (64 characters)
#   - Keys are stored hashed (SHA-256) in the local database — the raw key
#     is never stored on the gateway
#   - Key revocation: An admin can mark a key as revoked in the key store,
#     immediately blocking that device from accessing the API
#   - Key rotation: New keys can be issued to ASHAs via the /sync/ endpoint
#     after identity verification by the PHC Medical Officer
#
# AUTHORIZATION:
#   Role-based access control with two roles:
#     - ASHA: Can access /triage/ and /sync/ endpoints only
#     - ADMIN: Can access all endpoints including /health/status and key
#       management (typically the PHC Medical Officer)
#
# FASTAPI INTEGRATION:
#   Exposes a FastAPI Depends() dependency that route handlers use:
#     async def assess_patient(current_user: ASHAUser = Depends(authenticate)):
#       ...
#   The authenticate() function reads the X-API-Key header, validates it,
#   and returns an ASHAUser object (asha_id, role, last_active).
#
# AUDIT LOGGING:
#   Every authentication attempt (success or failure) is logged with:
#   - timestamp, source_ip, api_key_prefix (first 8 chars), asha_id, result
#   Failed attempts above a threshold trigger an alert (logged as WARNING).
#
# MQTT AUTHENTICATION:
#   For BLE-to-MQTT sensor data flow, authentication is handled by the
#   Mosquitto broker's plugin config (see mqtt_broker_config/). This module
#   handles only HTTP API authentication.
# =============================================================================
