[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200

lib_deps =
    ESP32 BLE Arduino
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    bogde/HX711 @ ^0.7.5
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

lib_extra_dirs =
    ../../edge_impulse/export

build_flags =
    -DARDUINO_ARCH_ESP32

board_build.partitions = huge_app.csv
