# =============================================================================
# AyushBot Backend — Agent 3: Referral Planning Agent (The Logistician)
# =============================================================================
#
# PURPOSE:
#   This agent creates a deterministic, actionable referral plan based on the
#   diagnosis from Agent 2 and the risk level from Agent 1. It handles three
#   distinct responsibilities: facility routing, drug dosage calculation, and
#   action plan generation. ALL outputs are deterministic — no LLM-based
#   probabilistic reasoning occurs in this agent.
#
# INPUTS (from Patient State Object):
#   - differential_diagnosis: ranked list from Agent 2
#   - risk_level: risk badge from Agent 1
#   - validated_vitals: current vital signs
#   - patient_demographics: age, weight, sex
#   - location: GPS coordinates or village/PHC identifier (from ASHA phone)
#
# PROCESSING STEPS:
#
#   Step 1 — Referral Destination Selection (Rule-Based)
#     Based on the primary diagnosis + risk level, determine the appropriate
#     facility tier using a deterministic decision table:
#       - CRITICAL → District Hospital (highest tier available)
#       - HIGH + specific conditions → Community Health Centre (CHC)
#       - MEDIUM → Primary Health Centre (PHC)
#       - LOW → Home management with ASHA follow-up
#     The decision table is loaded from a YAML/JSON configuration file
#     that maps (condition, risk_level) → facility_tier.
#
#   Step 2 — Geographic Facility Routing (Dijkstra's Algorithm)
#     Given the required facility tier and the ASHA's current location:
#     a. Load the local road network graph (nodes = villages/facilities,
#        edges = roads with distance/travel-time weights)
#     b. Run Dijkstra's shortest-path algorithm from current location to
#        the nearest facility of the required tier
#     c. Return: facility name, address, distance (km), estimated travel
#        time (minutes), and the route description
#     The road graph is pre-built from OpenStreetMap data for the PHC's
#     coverage area and stored as a compressed adjacency list.
#
#   Step 3 — Drug Dosage Calculation (Deterministic Math)
#     For conditions that require immediate medication (e.g., oral
#     rehydration salts for diarrhea, paracetamol for fever, amoxicillin
#     for pneumonia):
#     a. Look up the drug protocol from the RAG-retrieved evidence chunks
#        or from a bundled drug formulary (JSON/YAML)
#     b. Calculate the dose using the patient's weight:
#        dose_mg = weight_kg × dose_per_kg_mg
#     c. Apply age-based caps and contraindication checks
#     d. Format the prescription in ASHA-friendly language:
#        "Give [Drug] [Dose] mg, [Frequency], for [Duration]"
#     ALL DOSAGE CALCULATIONS ARE PURE ARITHMETIC — never LLM-generated.
#
#   Step 4 — Action Plan Assembly
#     Combine referral destination + drug instructions + immediate care
#     steps into a structured ActionPlan Pydantic object:
#       - urgency: enum (IMMEDIATE, WITHIN_24H, WITHIN_WEEK, ROUTINE)
#       - referral_facility: name, address, distance, travel_time
#       - medications: list of drug objects (name, dose, frequency, duration)
#       - immediate_actions: list of strings (e.g., "Keep child hydrated",
#         "Monitor breathing every 2 hours")
#       - follow_up: when the ASHA should re-visit (if home management)
#       - referral_slip: structured data for generating a PDF/image slip
#
# OUTPUTS (written to Patient State Object):
#   - action_plan: ActionPlan Pydantic object (defined in schemas/action_plan.py)
#   - routing_result: dict with facility details + Dijkstra path info
#   - prescriptions: list of calculated drug dosages
#
# SAFETY CONSTRAINTS:
#   - Drug dosages are NEVER generated by an LLM. They are always computed
#     from a validated formulary using deterministic arithmetic.
#   - Every drug recommendation includes the source guideline citation
#     (e.g., "MoHFW Standard Treatment Guidelines, Chapter 5, Table 3")
#   - Contraindication flags are checked against age, weight, and known
#     allergies (if recorded in patient history).
#   - If the patient's weight is unknown (sensor failed), the system uses
#     age-based weight estimation from WHO growth charts rather than guessing.
#
# DATA DEPENDENCIES:
#   - Road network graph: pre-built, stored as pickle/JSON in data/
#   - Drug formulary: YAML/JSON file bundled in backend/
#   - Referral decision table: YAML/JSON config file
#   - WHO growth charts: static lookup tables
#
# LATENCY TARGET: < 100 ms (routing ~50 ms + dosage ~10 ms + assembly ~10 ms)
# =============================================================================
