#!/usr/bin/env python3
"""
train_tinyml.py
===============
AyushBot — Model 1: TinyML Binary Danger-Sign Classifier
Target hardware : ESP32-WROOM (Edge Impulse / TFLite Micro INT8)
Dataset         : datasets/tinyml_new_dataset.csv  (generated by gen_tinyml_dataset.py)

Pipeline:
  ▸ Impute missing values (SpO2/HR dropout from sensor)
  ▸ Clip sensor glitches
  ▸ Exclude debug columns (_p_danger)
  ▸ Stratified split  70 / 15 / 15
  ▸ SMOTE on training fold only  (danger ~17–22% → balanced)
  ▸ Threshold sweep on val set  → recall ≥ 0.88 (safety-critical)
  ▸ Decision Tree (depth ≤ 5) vs Random Forest (10 trees)
  ▸ Final evaluation on held-out test set
  ▸ Export: .pkl / .json / evaluation plots / tree diagram

Expected realistic results:
  AUC    : 0.85 – 0.96
  Recall : 0.88 – 0.97
  F1     : 0.72 – 0.90

INSTALL:
  pip install numpy pandas scikit-learn imbalanced-learn matplotlib joblib
"""

import os, json, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

from sklearn.impute import SimpleImputer
from sklearn.tree   import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import (classification_report, confusion_matrix,
                              ConfusionMatrixDisplay, roc_auc_score, RocCurveDisplay,
                              f1_score, recall_score, precision_score, roc_curve)
from imblearn.over_sampling import SMOTE

warnings.filterwarnings("ignore")
os.makedirs("tinyml", exist_ok=True)

FEATURES = [
    "age_months",
    "spo2_current",
    "hr_current",
    "temperature_c",
    "delta_spo2_30s",
    "delta_hr_30s",
]
LABEL = "danger_label"

# ── 1. LOAD ──────────────────────────────────────────────────────────────────
print("\n[1/8] Loading dataset...")
df = pd.read_csv("datasets/tinyml_dataset_clean.csv")
print(f"      Rows: {len(df):,}  |  Columns: {list(df.columns)}")
print(f"      Class distribution:\n{df[LABEL].value_counts()}")

# ── 2. PREPROCESSING ─────────────────────────────────────────────────────────
print("\n[2/8] Preprocessing...")

# Clip sensor glitches before imputation
df["spo2_current"] = df["spo2_current"].clip(50, 100)
df["hr_current"]   = df["hr_current"].clip(30, 250)

# Report missingness
for col in FEATURES:
    n_miss = df[col].isna().sum()
    if n_miss: print(f"      Missing in {col}: {n_miss} ({n_miss/len(df)*100:.1f}%)")

X_raw = df[FEATURES].values
y     = df[LABEL].values

# Median imputation (robust to outliers)
imputer = SimpleImputer(strategy="median")
X = imputer.fit_transform(X_raw)

# ── 3. SPLIT ─────────────────────────────────────────────────────────────────
print("\n[3/8] Splitting: 70% train | 15% val | 15% test ...")
X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp, test_size=0.1765, random_state=42, stratify=y_temp)
print(f"      Train: {len(X_train):,}  Val: {len(X_val):,}  Test: {len(X_test):,}")
print(f"      Danger rate  train: {y_train.mean()*100:.1f}%  "
      f"val: {y_val.mean()*100:.1f}%  test: {y_test.mean()*100:.1f}%")

# ── 4. SMOTE (train fold only) ────────────────────────────────────────────────
print("\n[4/8] SMOTE on training fold only ...")
sm = SMOTE(sampling_strategy=0.50, random_state=42, k_neighbors=5)
X_sm, y_sm = sm.fit_resample(X_train, y_train)
print(f"      After SMOTE: {len(X_sm):,}  | "
      f"balance: {dict(zip(*np.unique(y_sm, return_counts=True)))}")

# ── 5. TRAIN ─────────────────────────────────────────────────────────────────
print("\n[5/8] Training models...")

DT = DecisionTreeClassifier(
    max_depth=5, min_samples_split=25, min_samples_leaf=12,
    class_weight="balanced", criterion="gini", random_state=42,
)
RF = RandomForestClassifier(
    n_estimators=12, max_depth=5,
    class_weight="balanced", random_state=42, n_jobs=-1,
)

DT.fit(X_sm, y_sm)
RF.fit(X_sm, y_sm)

# ── 6. THRESHOLD SWEEP on VAL ────────────────────────────────────────────────
print("\n[6/8] Threshold sweep on validation set (target recall ≥ 0.88)...")
val_probs = DT.predict_proba(X_val)[:, 1]
rf_probs  = RF.predict_proba(X_val)[:, 1]
best_dt_auc = roc_auc_score(y_val, val_probs)
best_rf_auc = roc_auc_score(y_val, rf_probs)
print(f"      DT Val AUC: {best_dt_auc:.4f}  |  RF Val AUC: {best_rf_auc:.4f}")

chosen_model = DT if best_dt_auc >= best_rf_auc else RF
chosen_probs = val_probs if chosen_model is DT else rf_probs
model_name   = "DecisionTree" if chosen_model is DT else "RandomForest"
print(f"      Selected   : {model_name}")

# sweep thresholds [0.15 → 0.55]
best_thresh, best_val_f1 = 0.35, -1
print(f"      {'Threshold':>10}  {'Recall':>8}  {'Precision':>10}  {'F1':>8}")
for t in np.arange(0.15, 0.56, 0.05):
    pred = (chosen_probs >= t).astype(int)
    rec  = recall_score(y_val, pred, zero_division=0)
    prec = precision_score(y_val, pred, zero_division=0)
    f1   = f1_score(y_val, pred, zero_division=0)
    print(f"      {t:>10.2f}  {rec:>8.4f}  {prec:>10.4f}  {f1:>8.4f}")
    if rec >= 0.88 and f1 > best_val_f1:
        best_thresh, best_val_f1 = t, f1

print(f"\n      → Best threshold: {best_thresh:.2f}  (F1={best_val_f1:.4f})")

# 5-fold CV
cv_scores = cross_val_score(
    chosen_model, X_sm, y_sm,
    cv=StratifiedKFold(5, shuffle=True, random_state=42),
    scoring="roc_auc")
print(f"      5-Fold CV AUC : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# ── 7. TEST EVALUATION ────────────────────────────────────────────────────────
print("\n[7/8] Evaluating on held-out test set...")
test_probs = chosen_model.predict_proba(X_test)[:, 1]
test_preds = (test_probs >= best_thresh).astype(int)
t_auc  = roc_auc_score(y_test, test_probs)
t_rec  = recall_score(y_test, test_preds)
t_prec = precision_score(y_test, test_preds)
t_f1   = f1_score(y_test, test_preds)

print("\n      === TEST SET RESULTS ===")
print(classification_report(y_test, test_preds, target_names=["Safe (0)", "Danger (1)"]))
print(f"      AUC={t_auc:.4f}  Recall={t_rec:.4f}  Precision={t_prec:.4f}  F1={t_f1:.4f}")

targets_met = []
if t_auc   >= 0.85: targets_met.append("AUC ≥ 0.85 ✓")
else:               targets_met.append("AUC ≥ 0.85 ✗")
if t_rec   >= 0.88: targets_met.append("Recall ≥ 0.88 ✓")
else:               targets_met.append("Recall ≥ 0.88 ✗ (SAFETY RISK)")
print(f"      Targets : {' | '.join(targets_met)}")

# ── 8. PLOTS ─────────────────────────────────────────────────────────────────
print("\n[8/8] Generating plots...")

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle(f"TinyML Danger-Sign Classifier — {model_name}  "
             f"(threshold={best_thresh:.2f})", fontsize=13, fontweight="bold")

# Confusion matrix
ConfusionMatrixDisplay(confusion_matrix(y_test, test_preds),
                       display_labels=["Safe","Danger"]).plot(ax=axes[0], colorbar=False)
axes[0].set_title(f"Confusion Matrix\nRecall={t_rec:.3f}  Prec={t_prec:.3f}")

# ROC
axes[1].plot([0,1],[0,1],"--",color="gray",lw=1,label="Chance (0.50)")
RocCurveDisplay.from_predictions(
    y_test, test_probs, ax=axes[1],
    name=f"{model_name}  AUC={t_auc:.3f}")
# mark operating point
fpr, tpr, thresholds = roc_curve(y_test, test_probs)
op_idx = np.argmin(np.abs(thresholds - best_thresh))
axes[1].scatter(fpr[op_idx], tpr[op_idx], color="red", zorder=5, s=80,
               label=f"Operating point (t={best_thresh:.2f})")
axes[1].legend(fontsize=8)
axes[1].set_title("ROC Curve")

# Feature importance
imp = chosen_model.feature_importances_
idx = np.argsort(imp)
axes[2].barh(np.array(FEATURES)[idx], imp[idx], color="#2563EB")
axes[2].set_title("Feature Importance (Gini)")
axes[2].set_xlabel("Importance")
for i, v in enumerate(imp[idx]):
    axes[2].text(v + 0.002, i, f"{v:.3f}", va="center", fontsize=8)

plt.tight_layout()
plt.savefig("tinyml/tinyml_evaluation.png", dpi=150, bbox_inches="tight")
plt.close()
print("      Saved: tinyml/tinyml_evaluation.png")

# Tree diagram (DT only)
if model_name == "DecisionTree":
    fig2, ax_t = plt.subplots(figsize=(22, 9))
    plot_tree(chosen_model, feature_names=FEATURES, class_names=["Safe","Danger"],
              filled=True, rounded=True, fontsize=9, ax=ax_t)
    ax_t.set_title("Decision Tree Structure (max_depth=5)  "
                   "— Realistic Synthetic Data", fontsize=13)
    plt.tight_layout()
    plt.savefig("tinyml/tinyml_tree.png", dpi=120, bbox_inches="tight")
    plt.close()
    print("      Saved: tinyml/tinyml_tree.png")

# ── SAVE ARTEFACTS ────────────────────────────────────────────────────────────
joblib.dump(chosen_model, "tinyml/tinyml_model.pkl")
joblib.dump(imputer, "tinyml/tinyml_imputer.pkl")

metrics = dict(model=model_name, threshold=float(best_thresh),
               test_auc=round(t_auc,4), test_recall=round(t_rec,4),
               test_precision=round(t_prec,4), test_f1=round(t_f1,4),
               cv_auc_mean=round(cv_scores.mean(),4))
pd.DataFrame([metrics]).to_csv("tinyml/tinyml_metrics.csv", index=False)

with open("tinyml/tinyml_model.json","w") as f:
    json.dump({
        "model_type"  : model_name,
        "features"    : FEATURES,
        "threshold"   : float(best_thresh),
        "imputer"     : "median (tinyml_imputer.pkl)",
        "metrics"     : metrics,
        "notes": {
            "dataset": "Realistic synthetic (probabilistic labels, ~5% label noise, ~3% sensor dropout)",
            "edge_export": "Use micromlgen or ei-learn for INT8 C++ on ESP32-WROOM",
            "why_not_100": ("Perfect accuracy is a red flag on synthetic data. "
                            "Realistic overlap was added intentionally to prevent "
                            "model from learning trivial hard thresholds.")
        }
    }, f, indent=2)
print("      Saved: tinyml_model.pkl / tinyml_imputer.pkl / tinyml_metrics.csv / tinyml_model.json")

print(f"\n✅  TinyML training complete.")
print(f"    AUC={t_auc:.4f}  Recall={t_rec:.4f}  F1={t_f1:.4f}")
print(f"    (Expected range: AUC 0.85–0.96, Recall 0.88–0.97 — realistic with noisy synthetic data)")
